[package]
name = "engine-query"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.15", features = ["csr", "nightly"] }
reqwasm = "0.5.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_yaml = "0.9.34"
